language: go
dist: xenial

services:
  - docker

matrix:
  include:
    - env: GFAPI_APIS=legacy
    - env: GFAPI_APIS=enhanced

before_install: |
  make ci-image GFAPI_APIS=${GFAPI_APIS}

before_script:
  - make setup-test-container GFAPI_APIS=${GFAPI_APIS}

script:
  - make test-container GFAPI_APIS=${GFAPI_APIS}
